version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./conf.d/default.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=8000
      - TZ=Asia/Shanghai